import { Societe } from "app/models/societe.model";

export const _DATA_SOCIETE:Societe[] = [
	{
		id:1,
		"code": "Z6F5P5",
		"raison_sociale": "Orange Burkina SA",
		"adresse": "Ouagadougou, sect 28 rue 100",
		"ville": "Ouagadougou",
		"bp": "7118",
		"telephone": "+228 52369852",
		regime:'Commerciale', 
		sigle:'Orange BSA',
		rccm:'5215dscs',
		cnss:'',
		contribuable:'',
		statistique:'',
		activite:'',
		date_creation:'',
		date_mise_service:'',
		date_effet:'',
		date_immatriculation:'',
 		code_postal:'', 
 		fax:'',
		email:'',
		nif:'',
		source_donnees:'',
		code_residence:'',
		adressen:'',
		rue:'',
		lieu_dit:'',
		quartier:'',
		arrondissement:'',
		departement:'',
		province:''
	},
	{
		id:2,
		"code": "Z6F5P6",
		"raison_sociale": "Télécel Burkina",
		"adresse": "Bobo-Dioulasso, sect 28 rue 101",
		"ville": "Bobo-Dioulasso",
		"bp": "1025",
		"telephone": "+228 52369852",
		regime:'Commerciale', 
		sigle:'Orange BSA',
		rccm:'5215dscs',
		cnss:'',
		contribuable:'',
		statistique:'',
		activite:'',
		date_creation:'',
		date_mise_service:'',
		date_effet:'',
		date_immatriculation:'',
 		code_postal:'', 
 		fax:'',
		email:'',
		nif:'',
		source_donnees:'',
		code_residence:'',
		adressen:'',
		rue:'',
		lieu_dit:'',
		quartier:'',
		arrondissement:'',
		departement:'',
		province:''
	}
]